<a href="https://colab.research.google.com/github/IUDigital2024/Curso_Basico_Udemy_ML/blob/main/Curso_Udemy_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [6]:
import numpy as np

# Crear una lista de números secuenciales de 10 a 39
lista = list(range(10, 40))

# Convertir la lista en una matriz de 3 filas y 10 columnas
matriz = np.array(lista).reshape(3, 10)

print(matriz)


[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [7]:
#creando dataframe
filas = ['ventas1','ventas2','ventas3']
columnas = ['zonaA','zonaB','zonaC']
datos = [[123,321,432],[987,789,567],[456,654,765]]
dataframe = pd.DataFrame(datos, filas,columnas)
print(dataframe)

         zonaA  zonaB  zonaC
ventas1    123    321    432
ventas2    987    789    567
ventas3    456    654    765


In [8]:
dataframe.loc['ventas1']

zonaA    123
zonaB    321
zonaC    432
Name: ventas1, dtype: int64

In [9]:
dataframe.iloc[2]

zonaA    456
zonaB    654
zonaC    765
Name: ventas3, dtype: int64

In [10]:
dataframe.describe()

zonaA       zonaB       zonaC
count    3.000000    3.000000    3.000000
mean   522.000000  588.000000  588.000000
std    435.764845  240.879638  167.490298
min    123.000000  321.000000  432.000000
25%    289.500000  487.500000  499.500000
50%    456.000000  654.000000  567.000000
75%    721.500000  721.500000  666.000000
max    987.000000  789.000000  765.000000

In [11]:
#agregando columna al df
dataframe['Todas las columnas'] = dataframe['zonaA'] + dataframe['zonaB'] + dataframe['zonaC']
dataframe

zonaA  zonaB  zonaC  Todas las columnas
ventas1    123    321    432                 876
ventas2    987    789    567                2343
ventas3    456    654    765                1875

In [12]:
#eliminando la columna creada
dataframe.drop('Todas las columnas', axis= 1)
dataframe

zonaA  zonaB  zonaC  Todas las columnas
ventas1    123    321    432                 876
ventas2    987    789    567                2343
ventas3    456    654    765                1875

In [13]:
#para borrar la columna agregada del todo
dataframe.drop('Todas las columnas', axis=1, inplace= True)
dataframe

zonaA  zonaB  zonaC
ventas1    123    321    432
ventas2    987    789    567
ventas3    456    654    765

In [14]:
# Agregando una nueva columna 'zonaD' con los valores especificados
dataframe['zonaD'] = [234, 435, 790]
print(dataframe)

         zonaA  zonaB  zonaC  zonaD
ventas1    123    321    432    234
ventas2    987    789    567    435
ventas3    456    654    765    790


In [15]:
#seleccionando datos con una condicion
filas = 'ventas1 ventas2 ventas3'.split()
filas

['ventas1', 'ventas2', 'ventas3']

In [16]:
columnas = 'zonaA zonaB zonaC zonaD'.split()
columnas

['zonaA', 'zonaB', 'zonaC', 'zonaD']

In [17]:
#condicion
condicion = dataframe['zonaD']<435
dataframe[condicion]

zonaA  zonaB  zonaC  zonaD
ventas1    123    321    432    234

In [18]:
condicion = dataframe['zonaB']> 321
dataframe[condicion]

zonaA  zonaB  zonaC  zonaD
ventas2    987    789    567    435
ventas3    456    654    765    790

In [19]:
# Aplicando la condición
condicion = (dataframe['zonaA'] > 200) & (dataframe['zonaB'] > 300)
dataframe = dataframe[condicion] # Mostrar el dataframe filtrado
print(dataframe)

         zonaA  zonaB  zonaC  zonaD
ventas2    987    789    567    435
ventas3    456    654    765    790


In [20]:
#modificando el nombre de filas en un data frame
filas = ['ventas1','ventas2','ventas3']
columnas = ['zonaA','zonaB','zonaC']
datos = [[123,321,432],[987,789,567],[456,654,765]]
dataframe = pd.DataFrame(datos, filas,columnas)
print(dataframe)

         zonaA  zonaB  zonaC
ventas1    123    321    432
ventas2    987    789    567
ventas3    456    654    765


In [21]:
nuevas_filas = 'dia1 dia2 dia3'.split()
nuevas_filas

['dia1', 'dia2', 'dia3']

In [22]:
dataframe['dias'] =nuevas_filas
dataframe

zonaA  zonaB  zonaC  dias
ventas1    123    321    432  dia1
ventas2    987    789    567  dia2
ventas3    456    654    765  dia3

In [23]:
#ponemos dias como indice
dataframe.set_index('dias')

zonaA  zonaB  zonaC
dias                     
dia1    123    321    432
dia2    987    789    567
dia3    456    654    765

In [24]:
dataframe

zonaA  zonaB  zonaC  dias
ventas1    123    321    432  dia1
ventas2    987    789    567  dia2
ventas3    456    654    765  dia3

In [25]:
#para que el cambio de indice permanezca utilizo inplace = True
dataframe.set_index('dias', inplace=True)
dataframe

zonaA  zonaB  zonaC
dias                     
dia1    123    321    432
dia2    987    789    567
dia3    456    654    765

In [26]:
dataframe

zonaA  zonaB  zonaC
dias                     
dia1    123    321    432
dia2    987    789    567
dia3    456    654    765

In [27]:
#manejo de nulos
diccionario = {'A':[4,5,np.nan],
               'B':[6,1,5],
               'C':[np.nan,4,np.nan]}

In [28]:
dataframe = pd.DataFrame(diccionario)
dataframe

A  B    C
0  4.0  6  NaN
1  5.0  1  4.0
2  NaN  5  NaN

In [29]:
dataframe.dropna()

A  B    C
1  5.0  1  4.0

In [30]:
dataframe

A  B    C
0  4.0  6  NaN
1  5.0  1  4.0
2  NaN  5  NaN

In [31]:
#para que un metodo quede definitivo la accion debo escribir inplace = True
dataframe.dropna(axis=1, inplace = True)
dataframe

B
0  6
1  1
2  5

In [32]:
#para cambiar los null por un valor
diccionario = {'A':[4,5,np.nan],
               'B':[6,1,5],
               'C':[np.nan,4,np.nan]}

In [33]:
dataframe = pd.DataFrame(diccionario)
dataframe

A  B    C
0  4.0  6  NaN
1  5.0  1  4.0
2  NaN  5  NaN

In [34]:
dataframe.fillna(value = 100)


A  B      C
0    4.0  6  100.0
1    5.0  1    4.0
2  100.0  5  100.0

In [35]:
#reemplazando los nan con el promedio de cada columna

# Creando el DataFrame con los datos proporcionados
diccionario = {'A': [4, 5, np.nan],
               'B': [6, 1, 5],
               'C': [np.nan, 4, np.nan]}
dataframe = pd.DataFrame(diccionario)

# Calculando el promedio de cada columna
promedios = dataframe.mean()

# Reemplazando los NaN con el promedio de cada columna
dataframe.fillna(promedios, inplace=True)

print(dataframe)


     A  B    C
0  4.0  6  4.0
1  5.0  1  4.0
2  4.5  5  4.0


In [36]:
#agrupacion por columnas
diccionario ={'dias': ['dia1','dia1','dia2','dia2','dia3'],'vendedores':['Antonio','Maria','Jose','Marta','Juan'],
            'ventas': [100,400,200,500,300]}

In [37]:
dataframe = pd.DataFrame(diccionario)
dataframe

dias vendedores  ventas
0  dia1    Antonio     100
1  dia1      Maria     400
2  dia2       Jose     200
3  dia2      Marta     500
4  dia3       Juan     300

In [38]:
#agruparemos las ventas por dias, tendriamos apenas 3 filas
dataframe.groupby('dias').sum()

vendedores  ventas
dias                      
dia1  AntonioMaria     500
dia2     JoseMarta     700
dia3          Juan     300

In [40]:
#promedio de ventas

dataframe.groupby('dias').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [48]:
#combinando DF
import pandas as pd
df1 = {'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]}
concatenacion1 = pd.DataFrame(df1)
concatenacion1

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [49]:
df2 = {'A':[11,12,13],'B':[14,15,16],'C':[17,18,19]}
concatenacion2 = pd.DataFrame(df2)
concatenacion2

A   B   C
0  11  14  17
1  12  15  18
2  13  16  19

In [50]:
#para concatenar usamos el metodo concat()
pd.concat([concatenacion1,concatenacion2])


A   B   C
0   1   4   7
1   2   5   8
2   3   6   9
0  11  14  17
1  12  15  18
2  13  16  19

In [53]:
#los concatenaremos uno al lado del otro
pd.concat([concatenacion1,concatenacion2], axis = 1)

A  B  C   A   B   C
0  1  4  7  11  14  17
1  2  5  8  12  15  18
2  3  6  9  13  16  19

In [57]:
#uso de merge
import numpy as np
import pandas as pd

In [60]:
merge1 = {'A':[1,2,3],
          'B':[4,5,6],
          'clave':['c1','c2','c3']}
union1 = pd.DataFrame(merge1)
union1

A  B clave
0  1  4    c1
1  2  5    c2
2  3  6    c3

In [61]:
merge2 = {'C':[11,12,13],
          'D':[14,15,16],
          'clave':['c1','c2','c3']}
union2 = pd.DataFrame(merge2)
union2


C   D clave
0  11  14    c1
1  12  15    c2
2  13  16    c3

In [65]:
#vamos a usar merge o union.
pd.merge(union1,union2, on='clave')


A  B clave   C   D
0  1  4    c1  11  14
1  2  5    c2  12  15
2  3  6    c3  13  16

In [70]:
#uso de join

lista1 = {'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]}
dataframe1 = pd.DataFrame(lista1, index = ['i1','i2','i3'])
dataframe1

A  B  C
i1  1  4  7
i2  2  5  8
i3  3  6  9

In [73]:
lista2 = {'D':[10,11,12],
          'E': [13,14,15],
          'F':[16,17,18]}
dataframe2 = pd.DataFrame(lista2, index = ['i1','i2','i3'])
dataframe2

D   E   F
i1  10  13  16
i2  11  14  17
i3  12  15  18

In [74]:
dataframe1.join(dataframe2)

A  B  C   D   E   F
i1  1  4  7  10  13  16
i2  2  5  8  11  14  17
i3  3  6  9  12  15  18

#OPERACIONES CON DATAFRAMES

In [75]:
operacion = {'A': [1,2,3,4,2],'B':[10,11,12,13,14]}
resultado = pd.DataFrame(operacion)
resultado

A   B
0  1  10
1  2  11
2  3  12
3  4  13
4  2  14

In [76]:
#miremos los valores unicos del df
resultado['A'].unique()

array([1, 2, 3, 4])

In [77]:
#cuenta el numero de valores unicos. hay 4 por eso imprime como resultado 4 que son el 1,2,3,4. el dos esta repetido
resultado['A'].nunique()

4

In [78]:
resultado['A'].value_counts()

A
2    2
1    1
3    1
4    1
Name: count, dtype: int64

In [79]:
#para mostrar la salida en orden
resultado['A'].value_counts().sort_index()

A
1    1
2    2
3    1
4    1
Name: count, dtype: int64

In [80]:
#aplicando una funcion al df
def multiplicar(x):
    return x*2

